@hostname = http://localhost:3000
@id = 1736764994205




###get item
GET {{hostname}}/api/geotags?latitude=49.014993&longitude=8.390049&page=2

###post item
POST {{hostname}}/api/geotags
Content-Type: application/json

{
    "name": "TEST",
    "latitude": 48.87036,
    "longitude": 8.39479,
    "hashtag": "#test"
}



###get item with id
GET {{hostname}}/api/geotags/{{id}}


###put item with id
PUT  {{hostname}}/api/geotags/{{id}}
Content-Type: application/json

{
    "name": "TEST",
    "latitude": 48.87036,
    "longitude": 8.39479,
    "hashtag": "#123"
}


###delete item with id
DELETE  {{hostname}}/api/geotags/{{id}}

